
spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
